### PR TITLE
Mobile support 

### PR DESCRIPTION
**Pull request by mortslhawmit**
Was scrolling around in the bathroom looking for some poe2 tree and found this but noticed that it was hard to navigate on mobile so i thought i could give it a try to fix that.

Added touchevent handlers, got most inspiration from the from the mousevents handlers and tweeked abit where it was needed, have only tested on chrome on Android so feel free to test on more devices.

_Not really thet experienced in svelte so if there are obvoius mistaked please tell me and i can learn something! :)_

### CODE REVIEW

**Comment by marcoaaguiar** [comment]
Hey, this PR is awesome but I just merged a big addition by @neo-daru which has added conflicts to this PR, can you sync it with main?

**Comment by mortslhawmit** [comment]
The topbar was abit messed up so i made some small changes so github stuff is readable and clickable in mobile view aswell

**Comment by marcoaaguiar** [comment]
@neo-daru you are the one that did most of the UI work by now. Do you mind reviewing these changes?
I'm not on my computer right now, I can check it later today otherwise

**Comment by marcoaaguiar** [comment]
Closes #52

**Comment by Kehrweek** [comment]
It would be great if we could sync this merge request with #84

**Comment by mortslhawmit** [comment]
Sure I dont mind waiting for the tailwind stuff to be merged :)

**Comment by neo-daru** [comment]
> @neo-daru you are the one that did most of the UI work by now. Do you mind reviewing these changes? I'm not on my computer right now, I can check it later today otherwise

unfortunately I'm not able to review/test this right now and won't have much time to contribute this week

**Comment by marcoaaguiar** [comment]
For me would make sense to merge this before  the tailwind stuff since it came first and and it is the smaller PR, but if you prefer I can hold this

**Comment by Kehrweek** [comment]
If @mortslhawmit doesn’t mind, I’d appreciate it if this could be merged after #84. Otherwise, I’ll have to manually resolve the entire `+page.svelte` conflict again.

**Comment by marcoaaguiar** [comment]
@mortslhawmit I just merged the #84 if you can update your PR I will merge it :)

**Comment by Kehrweek** [comment]
If you need help to fix the new sidebar, i may help with that.

Current State:
image

**Comment by mortslhawmit** [comment]
Changed the sidebar abit to look nicer on smaller screens, added a button to toggle the sidebar aswell

image
image

**Comment by marcoaaguiar** [comment]
Synced with main and merged. Let me know if screwed up anything :)

**Comment by mortslhawmit** [comment]
Nice! Seems like the Button to close is triggerd when you press search ill give that a look when I can :)

**Pull request merged**
