### PR TITLE
feat: add nodes from havoc mercenary video

### PR DESCRIPTION
**Pull request by meatwallace**
add's nodes from [havoc's mercenary gameplay video](https://www.youtube.com/watch?v=MLUfCNS7Pgo).

this is an extension of #96 to minimize my own commit headaches. neither of these PRs are urgent - if there's other data that's easier to merge in when you get to it, i'll update & deconflict everything and make it headache free for everyone else.

### CODE REVIEW

**Comment by meatwallace** [comment]
@marcoaaguiar - can i ask what settings/tool you used to lint the description data file? i think it looks like you ran something across the whole file. i've started transcribing nodes from havoc's new merc video and immediately exploded the diff with an autorun of prettier (same output as `npm run format`)

happy to adjust tooling and rerun to minimize issues or can just do another prettier run as part of this commit, albeit it'll be full of noise which i can seperate out into it's own commit.

**Comment by marcoaaguiar** [comment]
It should have been prettier. The issues that you saw might have come from merging #74.
I going to continue discussion on #96

**Comment by meatwallace** [comment]
rebased & ready to go.

**Comment by marcoaaguiar** [comment]
Done!

**Pull request merged**
