### PR TITLE
Move Contribution Info To CONTRIBUTE.md

### PR DESCRIPTION
**Pull request by midastouchprd**
closes Issue #55

### CODE REVIEW

**Comment by midastouchprd** [comment]
i left contributers on the main readme since there's an action to fill it

**Comment by meatwallace** [comment]
i'd suggest the contribution notes are left in the main README.

for any other normal dev project, splitting it out is fine, but there's been a lot of contributors that have limited technical/development backgrounds from what i've observed and having a seperate doc means it's less intuitive for those types of folks to get started. just my 2c though

**Comment by marcoaaguiar** [comment]
I'm with @meatwallace on this

**Comment by Kehrweek** [comment]
We could link to it from the readme

**Comment by midastouchprd** [comment]
Happy to close this if that's what people think!

**Comment by marcoaaguiar** [comment]
Lets stick with contribution info in the main README. I'm closing this, I appreciate the effort in opening this PR

**Pull request closed without merging**
