### PR TITLE
Add TailwindCss and Component Cleanup

### PR DESCRIPTION
**Pull request by Kehrweek**
I added TailwindCss to this project and converted existing features using css to use tailwind.

- The header is a separate component now due to the page getting longer and longer.
- Overlays are now shown on the left instead of in the middle of the screen.
- Reduced a lot of css lines (i added tailwind for this)
- _and i ran `npm run format` (that's the reason for the number of files changed. But i didn't commit the nodes and desc to avoid mergeconflicts)_ 

If you have ideas, please leave a comment.

Preview:
image

Further Improvements:
- Extract Tree View into seperate Component File
- Remove remaining css code / put in separate file
- Move Selected/Search into Component

Rel: #82

### CODE REVIEW

**Comment by Kehrweek** [comment]
next step would be to use an ui component library. _(Maybe [Shadcn-Svelte](https://next.shadcn-svelte.com)?)_

**Comment by marcoaaguiar** [comment]
Thanks for this PR, everything in the same file was making me nervous 😄  moving abstractions to its own components makes complete sense. 
Next steps I believe would be to move the nodes and tooltips to their own components.
Regarding tailwind I have no opinion on that so I don't mind it being included in the project.

I will take a proper look on this PR when I get back on the computer in a couple of hours.
Do you mind syncing this with main?

**Comment by marcoaaguiar** [comment]
Also moving things to components reduces the odds of merge conflicts so I'm totally in favor of this direction

**Comment by Kehrweek** [comment]
I'm on it. had to rebase by repo tho. I will reopen when i'm done.

**Comment by Kehrweek** [comment]
I also moved the tooltip into a separate component to improve readability.

**Comment by lfmnovaes** [comment]
really good PR, if my PR #86 is also interesting, I can update mine after this merge to use tailwind classes too :)

**Comment by marcoaaguiar** [comment]
This looks great, the new UI feels even better
I think that the images will break on GH Pages since they are not using path.base. But I can fix if that happens

**Comment by Kehrweek** [comment]
@marcoaaguiar As you expected, the image is not loading. I will remember this when adding images in the future.

**Comment by marcoaaguiar** [comment]
https://github.com/marcoaaguiar/poe2-tree/commit/0481c8b9f1697c218c069ac0123c1fb36ec85685
Fixed it. This is because GH Pages sets the repository name in the base path. The build/routing expects that the project is served at the root (ie https://marcoaaguiar.github.io/) which is not the case

**Pull request merged**
