### PR TITLE
UI improvements v2

### PR DESCRIPTION
**Pull request by neo-daru**
- Hover feature for selected nodes and search results - click text to persist hover display
- Button to clear selected nodes
- localStorage to save selected nodes so they don't disappear on page refresh
- Default check true for `hide unidentified filter` (recommend from @meatwallace #18)
- Center image to show some class staring locations (modified the center picture from @shawnkfox from #20)

image

### CODE REVIEW

**Comment by marcoaaguiar** [comment]
I'm currently on mobile, I will check this once I'm back on the PC. Can you resolve the conflicts and sync it with main to make it easier merging?
Id really appreciate it

**Comment by neo-daru** [comment]
> I'm currently on mobile, I will check this once I'm back on the PC. Can you resolve the conflicts and sync it with main to make it easier merging? Id really appreciate it

sounds good, it should be fixed now

**Comment by neo-daru** [comment]
@marcoaaguiar 
I should note that there are more changes in #50, so it's probably better to merge that and close this

**Comment by marcoaaguiar** [comment]
I'm going to close this PR and merge #50

**Pull request closed without merging**
