### PR TITLE
feat: move tree node to its own component

### PR DESCRIPTION
**Pull request by marcoaaguiar**
Trying to reduce a bit the size of the page.svelte. Started by moving the node to its own component.
Not a lot reduced from script or html sections, but the styling section is gone :)

I would appreciate some review

### CODE REVIEW

**Comment by meatwallace** [comment]
haven't pulled & ran the project but the diff lgtm.

**Review by meatwallace — APPROVED** [review]

**Review by neo-daru — APPROVED** [review]
I tested locally and it works

**Comment by Kehrweek** [comment]
I'd personally change parameters like scale and tree related values to context variables. So the entire tree can be a component later and the nodes just use the tree context.

**Comment by Kehrweek** [comment]
I'm currently on my phone and will take a better look at it when i'm at my computer tomorrow. Its 9pm here

**Pull request merged**
