### PR TITLE
Ascendancy support

### PR DESCRIPTION
**Pull request by Giusti**
Here is my initial draft PR for ascendancy support, sadly i dont have more time this weekend to complete it

**What is already there:**
- Added a dropdown to the header section with the available ascendancies
- Added new skilltree images for a few ascendancies (they are not perfect but I guess good enough)
- Added logic to switch tree image based on dropdown selection

**What is missing:**
- Parsing or manually adding ascendancy nodes to a seperate node file for each ascendancy
- Adding ascendancy nodes based on dropdown selection to the node tree

Feel free to continue / adapt if you have time

### CODE REVIEW

**Comment by Giusti** [comment]
@marcoaaguiar I added images for all ascendancies, not sure if the python script can be easily adapted to scan the ascendancy nodes aswell or if doing it manually makes more sense (~100 nodes)

**Comment by Giusti** [comment]
Updated the PR as follows

1. Added Ascendancy Dropdown to the top of the Filters

image


2. Added Skilltree images for the respective ascendancies, for example bloodmage

image

3. Added Nodes for the Ascendancy AS (small ascendancy node) & AN (ascendancy notable)

Note: currently I only added 1 small & 1 big node for each ascendancy to have the base in place so people can update freely

image

@marcoaaguiar let me know if the current state is fine for you

**Comment by marcoaaguiar** [comment]
This is awesome! Having ascendancy support would be great for supporting full build planing!
I just merged a big PR from @Kehrweek (#84) can you sync your branch with main and will merge it

**Comment by marcoaaguiar** [comment]
Also i would move the ascendancy filtering to the loadData function so it only return the nodes for the selected ascendency. 
Also, in that case you wouldn't need to return the "class" attribute on the nodes.

**Comment by Giusti** [comment]
@marcoaaguiar I updated the PR and incorporated the tailwind changes & fixed merge conflicts

**Note**: I tried moving the filter into the load data function, which would work but whenever I would switch the ascendancy it would need to reload all the nodes or create seperate logic to only replace the ascendancy nodes.

I left a Todo comment as an improvement above the ascendancy filter function.

Will check back after work.

**Comment by marcoaaguiar** [comment]
Thanks! I see the problem lets leave as is now I if it makes sense refactor it later
Another point that might be worth refactoring is separating the Ascendency tree image from the rest of the tree and only overlay them whe displaying.
The reasoning is that the general passive tree is known to not be correct there have been some edits "stitching" updates. Having 12 trees increases this effort significantly.

**Comment by Giusti** [comment]
@marcoaaguiar 

- added independant ascendancy images (without skilltree)
- added skilltree ascendancy image overlay

**Comment by marcoaaguiar** [comment]
Its looking awesome, merged!

**Pull request merged**
